### PR TITLE
oci: remove 'drivers' abstraction

### PR DESCRIPTION
**Pull request by cyphar**
This effectively soft-reverts 184ab749f39a ("oci: cas: switch to
driver-based model for CAS"), which was effectively a mistake. The
concept of drivers doesn't make too much sense -- we are unlikely to
ever have more than one driver (unless we add remote backends).

Signed-off-by: Aleksa Sarai <asarai@suse.de>

### CODE REVIEW

**Comment by cyphar** [comment]
LGTM.

**Comment by cyphar** [comment]
(@hallyn: This is one of the changes that I mentioned.)

**Comment by hallyn** [comment]
Seems reasonable.

**Comment by cyphar** [comment]
LGTM.

**Pull request merged**
