### PR TITLE
.: remove LICENSE boilerplate

### PR DESCRIPTION
**Pull request by cyphar**
Remove LICENSE as it confuses GitHub's automated license detection. The
header in every file describing the license is sufficient. Not to
mention that there's also a COPYING in the root of the source tree with
the full license text.

I could rant for several hours about how insanely stupid GitHub's
license detection code is, and that it's just ridiculous that they don't
allow people to add boilerplate to projects -- because it makes it
impossible to have a standard way of telling contributors what the
project's full license terms are.

For instance, if you have a project under a GPLvX-or-later license, it
is not sufficient to just have a COPYING with the GPLvX license text --
you also need to include in the license header that it is licensed under
"GPLvX *or later*". Yes, you can (and should) include the header in all
source files, but that means that someone reviewing the license of your
project would have to *read every license header in the project* to be
sure of your project's licensing stance wrt. the or-later clause in the
GPL.

What insanity. Why didn't they just do what GNU Savannah did and allow
users to specify their license manually?

Signed-off-by: Aleksa Sarai <asarai@suse.de>

### CODE REVIEW

**Comment by cyphar** [comment]
LGTM

**Comment by wking** [comment]
On Mon, Feb 20, 2017 at 12:52:08PM -0800, Aleksa Sarai wrote:
> I could rant for several hours about how insanely stupid GitHub's
> license detection code is, and that it's just ridiculous that they don't
> allow people to add boilerplate to projects -- because it makes it
> impossible to have a standard way of telling contributors what the
> project's full license terms are.

You can add boilerplate to the project by putting a note in the
README.  Licensee won't look there [1], and while I don't know if it's
standardized anywhere, the CII repo [2] and Docker's open-source
template [3] both have a README section on licensing.

[1]: https://github.com/benbalter/licensee/blob/v8.7.0/docs/what-we-look-at.md#what-about-looking-to-see-if-the-author-said-something-in-the-readme
[2]: https://github.com/linuxfoundation/cii-best-practices-badge/blob/0.8.0/README.md#license
[3]: https://github.com/docker/opensource/blob/036b4241bbdc42228c0f79dee379e5a76a5fdbae/project-template/README.md#copyright-and-license

**Comment by cyphar** [comment]
@wking I already have the boilerplate in the README...

**Comment by wking** [comment]
On Mon, Feb 20, 2017 at 02:15:55PM -0800, Aleksa Sarai wrote:
> @wking I already have the boilerplate in the README...

+1 (and way back in 9e0a64684).  Sorry for trailing along and trying
to be helpful by responding to your motivation messages without
digging deeper.  Is there a reason you'd added the same blurb to both
the README and LICENSE in 9e0a6468?

And I also see that Licensee is correctly identifying your license now
[1]:

  $ curl -sH 'Accept: application/vnd.github.drax-preview+json' https://api.github.com/repos/openSUSE/umoci/license | jq -r .license.spdx_id
  Apache-2.0

[1]: https://developer.github.com/v3/licenses/#get-the-contents-of-a-repositorys-license

**Comment by cyphar** [comment]
> Is there a reason you'd added the same blurb to both
the README and LICENSE in 9e0a646?

While most people like having the boilerplate in `README`, I don't because there's no real "standard" way of declaring the license in a README. COPYING is for the license text, and COPYRIGHT is usually used for mixed things so I put the boilerplate in LICENSE to make it clear whether there are any additional terms or whether something is `GPLvX-or-later`.

It's probably overkill, but it also helps when I have to copy-paste the text to a source code file that has different commenting style to the other files in the repo (for example a `Makefile` as opposed to a `.c` file).

**Comment by wking** [comment]
On Mon, Feb 20, 2017 at 02:29:52PM -0800, Aleksa Sarai wrote:
> I put the boilerplate in LICENSE…

Is there a spec/precedence for that?  I think the usual approach is to
put the license text in either COPYING [1] or LICENSE [2].

> …to make it clear whether there are any additional terms or whether
> something is `GPLvX-or-later`.

If you are uncomfortable with the README blurb, I'd recommend
LICENSE.spdx [3,4,5].  The .spdx extension suggestion is new in SPDX
2.1 [6].  It can be pretty short and sweet (e.g. [7]), and they
suggest you do not inline the license text if the license is already
in the SPDX License List [8].  The downside is that LICENSE.spdx seems
uncommon in the wild [9], so you'd be providing machine-readable
content which nobody was likely to feed into a machine ;).

[1]: $ curl -s https://www.gnu.org/licenses/gpl-howto.html | grep -B1 COPYING
     text version of the GPL</a>.  In GNU programs the license is usually in
     a file called COPYING.</p>
     --
     include <a href="/licenses/lgpl.txt">the text version of the LGPL</a>,
     usually in a file called COPYING.LESSER.  Please note that, since the
[2]: https://github.com/github/choosealicense.com/blob/d99a0a9b4d573dbb1c25159a8eee39ce2baba36b/_licenses/apache-2.0.txt#L11
     how: Create a text file (typically named LICENSE or LICENSE.txt)…
[3]: https://github.com/linuxfoundation/cii-best-practices-badge/blob/5da838f66652d459156e03393a358db8969ca45b/criteria.yml#L145-L147
[4]: https://github.com/david-a-wheeler/spdx-tutorial/blame/99c84fd074564a991b79169e7e6eeb07f22d6475/README.md#L186
[5]: https://github.com/benbalter/licensee/issues/85
[6]: https://bugs.linuxfoundation.org/show_bug.cgi?id=1329
[7]: https://github.com/david-a-wheeler/spdx-tutorial/blob/99c84fd074564a991b79169e7e6eeb07f22d6475/LICENSE.spdx
[8]: https://spdx.org/spdx-specification-21-web-version#h.plv6rmeixwvj
[9]: https://github.com/search?utf8=%E2%9C%93&q=spdxversion+extension%3Aspdx&type=Code&ref=searchresults

**Pull request merged**
