### PR TITLE
Makefile: disable SELinux for tests in Docker

### PR DESCRIPTION
**Pull request by jonboulle**
Re-do of #203. As discussed there, there are outstanding SELinux issues with the tests even if we avoid the labelling one.

With the current Makefile, the Docker variants of the tests don't work
out of the box on SELinux-enabled systems because the volume mount
(namely, the source directory) isn't labelled correctly. This patch
simply disables SELinux labelling for these particular containers,
as the easiest way to mitigate this issue. (This seems preferable to
using the `:z` or `:Z` option to the Docker volume mount, which would
forceably relabel the directory every time the Docker command is run.)

Signed-off-by: Jonathan Boulle <jonathanboulle@gmail.com>

### CODE REVIEW

**Comment by cyphar** [comment]
Needs a rebase.

**Comment by jonboulle** [comment]
done

**Comment by cyphar** [comment]
LGTM.

**Comment by cyphar** [comment]
Travis failure is quite odd. It looks like the `skopeo copy docker://fedora:latest ...` is blocking indefinitely for some reason.

**Comment by cyphar** [comment]
LGTM.

**Pull request merged**
