### PR TITLE
docker build fails

### PR DESCRIPTION
**Pull request by ryanolson**
simple fix to the dockerfile

### CODE REVIEW

**Comment by cyphar** [comment]
Thanks, but we need `go-mtree` for the tests. I guess I must've dropped it from an openSUSE repo without noticing. I'll fix that up.

**Comment by ryanolson** [comment]
go-mtree is in the vendor directory, so you include it, just not via the package manager.

**Comment by cyphar** [comment]
@ryanolson We also use it as a binary, not just as a library. [In the tests, we do verification that `gomtree` succeeds after unpacking and so on.](https://github.com/openSUSE/umoci/blob/599ec5b416b25fce508249bd86e7bb62cf1e3308/test/unpack.bats#L50)

**Comment by cyphar** [comment]
This has been fixed in #176. Thanks for your patience, there were a lot of issues to deal with.

**Pull request closed without merging**
