### PR TITLE
README.md: fix links and formatting

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by cyphar** [comment]
While you're fixing up the `README`, would you mind re-generating the example with the latest version of `umoci`?

**Comment by cyphar** [comment]
I'll merge this and do the README rewrites later.

**Comment by cyphar** [comment]
LGTM

**Comment by cyphar** [comment]
Don't worry about fixing up the docs @runcom -- I'll just merge this anyway. But can you rebase it?

**Comment by runcom** [comment]
@cyphar rebased, sorry, couldn't find the time to re-run the example and fix this.

**Comment by cyphar** [comment]
LGTM.

Don't sweat it. :wink:

**Pull request merged**
