### PR TITLE
Api v2

### PR DESCRIPTION
**Pull request by tych0**
Hi,

This is a (much smaller and less fiddly) alternative to #219. The basic idea is that we don't wrap anything: we just expose `casext.Engine` and let people muck with that, the same way umoci itself does.

I've also included some public-ifying of additional code that I found useful.

Thoughts are welcome, but hopefully this is much less obnoxious than the other one :)

### CODE REVIEW

**Comment by tych0** [comment]
I rebased this after the dirlinks merge :)

**Comment by cyphar** [comment]
There was a minor CI failure, I've fixed it.

**Comment by cyphar** [comment]
@tych0 We should probably add a copyright line to the new files -- what line would you find appropriate?

**Comment by tych0** [comment]
Copyright (C) Cisco Systems 2018

Is good :-)

Thanks!

**Pull request merged**
