### PR TITLE
Update quickstart URL to point to website.

### PR DESCRIPTION
**Pull request by maxking**
Tiny change to update quickstart URL in README.

### CODE REVIEW

**Comment by cyphar** [comment]
You need to add a `Signed-off-by:` line to your commit(s) which indicates that you attest the [Developer Certificate of Origin](https://developercertificate.org/) a statement about your contributions that you *must read* before signing (don't worry, it's quite short and easy-to-read). You can add it to your commits with `git commit --amend -s`, and then doing a `git push --force`.

**Comment by maxking** [comment]
Done!

**Comment by cyphar** [comment]
LGTM.

**Comment by cyphar** [comment]
Sorry, I accidentally pushed `master` to your branch (I was doing a `rebase` since that's required for merging into this repo) -- which closed this pull request and I cannot re-open it. Can you please open a new PR (or I can do it if you prefer)?

**Pull request closed without merging**
